# Site settings
title: .net初学者
description: >
  喜欢代码

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sessionliang.github.io" # the base hostname & protocol for your site

author:
  fullname: Motaquillah Maddane
  #googleplus: https://www.google.com/+MotaquillahMaddane
  github: sessionliang
  #twitter: electrik_frog
  # disqus: your_disqus_username

# google_analytics: 'UA-XXXXXXXX-X'

# Build settings
markdown: kramdown